ingress:
  corsAllowOrigin: "https://awakari.com"
  hosts:
    - host: pub.awakari.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: secret-pub-tls-server
      hosts:
        - pub.awakari.com

# prod
cert:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
  issuer:
    name: letsencrypt


db:
  tls:
    enabled: true
    insecure: true
